---
title: "strings and foactors"
author: "Kwangmin Kim"
date: "November 2, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---
### NYC inspection
```{r}
library(tidyverse)
library(janitor)
library(haven)
library(rvest)

library(stringr)
library(forcats)

theme_set(theme_bw())
theme_update(legend.position = "bottom")


```
import data set

```{r}
nyc_inspections = read_csv("../data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz",                 col_types = cols(building = col_character()),
                           na = c("NA", "N/A"))

nyc_inspections %>% 
  group_by(boro,grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)

```

clean this data
```{r}
nyc_inspections =
  nyc_inspections %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))
```

search for pizza

```{r}
nyc_inspections %>% 
  filter(str_detect(dba, "Pizza")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)

```

better search for pizza
```{r}
nyc_inspections %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)

```

make a barplot
```{r}
nyc_inspections %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>%
  ggplot(aes(x = boro, fill = grade)) + geom_bar()
```

reorder the bar plot
```{r}
nyc_inspections %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>%
  mutate(boro = fct_infreq(boro)) %>%
  ggplot(aes(x = boro, fill = grade)) + geom_bar()
```

```{r}
nyc_inspections%>%
  select(Boro= boro, everything())

nyc_inspections %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>%
  mutate(boro = fct_infreq(boro),
         boro = fct_recode(boro, "Hipsterville" = "Brooklyn")) %>%
  ggplot(aes(x = boro, fill = grade)) + geom_bar()

```

```{r}
nyc_inspections %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>%
  mutate(boro = fct_infreq(boro),
         boro = fct_recode(boro, "Hipsterville" = "Brooklyn")) %>%
  ggplot(aes(x = boro, fill = grade)) + geom_bar()
```
