---
title: "webpage_reading"
author: "Kwangmin Kim"
date: "October 25, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(haven)
library(rvest)
library(janitor)
library(haven)
library(rvest)
library(stringr)
library(forcats)
library(httr)
```

##scraping

### NSDUH table
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

drug_use_xml
```


```{r}
drug_use_xml %>%
  html_nodes(css = "table")
```

got the tables

```{r}
table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table() %>%
  .[-1,]%>%
  as_tibble()

```

```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")

nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()


brfss = 
  GET("https://chronicdata.cdc.gov/api/views/hn4x-zwk7/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")


poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name

```


learning assignment
```{r}
url2= "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
cost_of_living = read_html(url2)

table_cost = (cost_of_living %>% html_nodes(css = "table"))[[2]]%>%html_table(header =TRUE)

```

##HP_SS Cast

got the names
```{r}

url = "http://www.imdb.com/title/tt0241527/"

hpss_xml = read_html(url)

hpss_cast = hpss_xml %>%
  html_nodes(css = ".itemprop .itemprop")%>%
  html_text()

```

##Deantal hygiegne;;kdsdf
```{r}
url = "https://www.amazon.com/Philips-Sonicare-rechargeable-toothbrush-HX6211/product-reviews/B00YAR7ZFM/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1"

toothbrush_xml = read_html(url)
toothbrush_title = toothbrush_xml%>%
  html_nodes(css = "#cm_cr-review_list .a-color-base")%>%
  html_text()

toothbrush_stars = toothbrush_xml%>%
  html_nodes(css = "#cm_cr-review_list .review-rating")%>%
  html_text()

toothbrush_df = data.frame(
title = toothbrush_title,
stars = toothbrush_stars
)

## APIs

### water use data


nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")

getwd()
```

