---
title: "reading_data_from_the_web.Rmd"
author: "Kwangmin Kim"
date: "October 25, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
drug_use_xml

drug_use_xml %>%
  html_nodes(css = "table")

table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table()%>%
  .[-1,] %>% 
  as_tibble()

hpss_html = read_html("http://www.imdb.com/title/tt0241527/")

cast = hpss_html %>%
  html_nodes(".itemprop .itemprop") %>%
  html_text()


```

##API
```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")

nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()


brfss = 
  GET("https://chronicdata.cdc.gov/api/views/hn4x-zwk7/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")


poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name
```
